name: CI

on:
  push:
    branches: [main, beta]
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          [
            'pnpm --filter overlay-kit-async run test',
            'pnpm --filter overlay-kit-async run test:attw',
            'pnpm --filter overlay-kit-async run test:publint',
            'pnpm lint',
            'pnpm --filter @overlay-kit/react-18 run build',
            'pnpm --filter @overlay-kit/react-19 run build',
            'pnpm --filter @overlay-kit/react-18 run test',
            'pnpm --filter @overlay-kit/react-19 run test',
          ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm --filter overlay-kit-async run build

      - name: Install Playwright Browsers
        if: contains(matrix.command, 'react-1') && contains(matrix.command, 'run test')
        run: pnpm --filter @overlay-kit/react-18 exec playwright install chromium --with-deps

      - name: Run command
        run: ${{ matrix.command }}
